# fly.toml app configuration file for transitpulse-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'transitpulse-backend'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '15s'
    method = 'GET'
    timeout = '5s'
    path = '/api/v1/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
